"""
1) MEMBRESIA
    -CORREO_SUSCRIPTOR:STR
    -NUMERO_TARJETA:STR

- METODO QUE PERTENECE A LA CLASE ABSTRACTA MEMBRESIA
_CREAR_NUEVA_MEMBRESIA() -> ES DE TIPO PROTECTED

TIPOS DE MEMBRESIA:
    - Gratis
    - Basica
    - Familiar
    - SinConexion
    - Pro

- CUANDO SE CREAN LAS MEEMBRESIAS RECIBEN VALORES FIJOS

- TODAS LAS MEBRESIAS DEBEN PODER PERMITR CAMBIAR DE SUSCRIPCION

- CUANDO SE REALICE ESTE PROCESO DEBE PERMITIR A LA MEBRESIA CAMBIAR DE TIPO DE MEMBRESIA CON UN IDENTIFICADOR NUMERICO DE LA MEMBRESIA SOLICITADA

1) BASICA
2) FAMILIAR
3) SIN CONEXION
4) PRO

DETALLE DE CADA MEMBRESIA:
- Gratis
    COSTO: 0
    CANTIDAD MAXIMA DE DISPOSITIVOS: 1

    - SI ALGUIEN CON ESTE TIPO DE MEMBRESIA DESEA CAMBIAR SU SUSCRIPCION DEBE VALIDAR QUE LA NUEVA MEMBRESIA SOLICITADA SEA UN NUMERO ENTRE 1 Y 4 INCLUSIVE, Y LUEGO GENERAR LA NUEVA MEMBRESIA. EN CASO CONTRARIO, DEBE RETORNAR LA MEMBRESIA ACTUAL

- Basica
    COSTO: 3000
    CANTIDAD MAXIMA DE DISPOSITIVOS: 2

    - SI ALGUIEN CON ESTE TIPO DE MEMBRESIA DESEA CAMBIAR SU SUSCRIPCION DEBE VALIDAR QUE LA NUEVA MEMBRESIA SOLICITADA SEA UN NUMERO ENTRE 2 Y 4 INCLUSIVE, Y LUEGO GENERAR LA NUEVA MEMBRESIA. EN CASO CONTRARIO, DEBE RETORNAR LA MEMBRESIA ACTUAL.

- Familiar
    COSTO: 5000
    CANTIDAD MAXIMA DE DISPOSITIVOS: 5
    DIAS DE REGALO: 7

    - SI ALGUIEN CON ESTE TIPO DE MEMBRESIA DESEA CAMBIAR SU SUSCRIPCION DEBE VALIDAR QUE LA NUEVA MEMBRESIA SOLICITADA SEA UN NUMERO ENTRE 1, 3 O 4, Y LUEGO GENERAR LA NUEVA MEMBRESIA. EN CASO CONTRARIO, DEBE RETORNAR LA MEMBRESIA ACTUAL.
    - DEBE PERMITIR MODIFICAR EL CONTROL PARENTAL. LA LOGICA DE ESTE COMPORTAMIENTO AUN NO SE HA DEFINIDO, PERO DEBE DECLARARLO (SIN IMPLEMENTACION)  

- SinConexion
    COSTO: 3500
    CANTIDAD MAXIMA DE DISPOSITIVOS: 2
    DIAS DE REGALO: 7

    - SI ALGUIEN CON ESTE TIPO DE MEMBRESIA DESEA CAMBIAR SU SUSCRIPCION DEBE VALIDAR QUE LA NUEVA MEMBRESIA SOLICITADA SEA UN NUMERO ENTRE 1, 2 O 4, Y LUEGO GENERAR LA NUEVA MEMBRESIA. EN CASO CONTRARIO, DEBE RETORNAR LA MEMBRESIA ACTUAL.
    - DEBE PERMITIR INCREMENTAR LA CANTIDAD MAXIMA DE CONTENIDO DISPONIBLE PARA VER SIN CONEXION. LA LOGICA DE ESTE COMPORTAMIENTO AUN NO SE HA DEFINIDO, PERO DEBE DECLARARLO (SIN IMPLEMENTACION) 

- Pro
    COSTO: 7000
    CANTIDAD MAXIMA DE DISPOSITIVOS: 6
    DIAS DE REGALO: 15

    - SI ALGUIEN CON ESTE TIPO DE MEMBRESIA DESEA CAMBIAR SU SUSCRIPCION DEBE VALIDAR QUE LA NUEVA MEMBRESIA SOLICITADA SEA UN NUMERO ENTRE 1 Y 3 INCLUSIVE, Y LUEGO GENERAR LA NUEVA MEMBRESIA. EN CASO CONTRARIO, DEBE RETORNAR LA MEMBRESIA ACTUAL.
    - DEBE PERMITIR MODIFICAR EL CONTROL PARENTAL (IGUAL A MEMBRESIA FAMILIAR)
    - DEBE PERMITIR INCREMENTAR LA CANTIDAD MAXIMA DE CONTENIDO DISPONIBLE PARA VER SIN CONEXION (IGUAL A MEMBRESIA SIN CONEXION)

- TODAS LAS MEMBRESIAS DEBEN PERMITIR CANCELAR LA SUSCRIPCION. AL REALIZAR ESTA ACCION, SE DEBE GENERAR UNA MEMBRESIA DE TIPO GRATIS CON EL MISMO CORREO Y NUMERO DE TARJETA DE LA MEMBRESIA ORIGINAL.

"""
